# Feed Forward

Install [Anaconda](https://www.anaconda.com/products/distribution)

Make sure that Python 3.9 is installed.

Install the following packages:
- numpy

## Numpy matrix basics

In [2]:
import numpy as np

# Initialize a numpy array of size (12, 4) and name it 'test'
# The values of the initalized array are to be created from a random normal distribution

# Code here (one line)
test = np.random.randn(12, 4)
print(f"TEST ARRAY = {test}")


# Transpose the matrix 'test' and override the initial matrix

# Code here (one line)
# test = test.T
# transposing the original array will cause error due to dimension mismatch and transposing the transposed array is of no use as it will give the original array


# Create a new numpy array of size (4, 3) and name it 'test_2' (initialized with a random uniform distribution with a low value of 0.1 and a high value of 0.9)
# Multiply (matrix multiplication) the matrix 'test' with the matrix 'test_2' respectively, and name the resulting matrix 'result'

# Code here
test_2 = np.random.uniform(low=0.1, high=0.9, size=(4,3))
result = np.dot(test, test_2)
print(f"RESULT {result}")


# Print the size (shape) of your 'result' matrix
result_shape = result.shape
print(f"RESULT SHAPE = {result_shape}")


# Slice the matrix 'result' so that
 # 1: the first until the fifth index of the first dimension and the last index of the second dimension are used (result matrix shape == (5, ))
 # 2: the last index of the first dimension and all indices of the second dimension are used (result matrix shape == (3,))
 # 3: every second index of the first dimension (starting from index 1 - NOT 0) and the first index of the second dimension are used (result matrix shape == (6,))

# Code here
slice_1 = result[0:5, -1]
slice_2 = result[-1, :]
slice_3 = result[1::2, 0]


# Find the maximum of the matrix 'result' in every dimension, so that the size of the first dimension stays the same and the second dimension is of size 1 (result matrix shape == (12,))
# Use a numpy pre-implemented function for it and name the resulting matrix 'max_result'

# Code here
max_result = np.max(result, axis=1)
print(f"MAX RESULT = {max_result}")


# Find the dimensional information where the max values are positioned in the 'result' matrix with a numpy function. Name the result matrix 'max_result_2'
# Use the dimensional information and slice the 'result' matrix by this information (neatly in a one-liner)

# Code here
max_result_2 = np.argmax(result, axis=1)
sliced_result = result[np.arange(result.shape[0]), max_result_2]
print(f"SLICED RESULT = {sliced_result}")


# Compare max_result and max_result_2. Are they the same?
# The comparison between the two matrix should either be True or False (not an array of True of False values)

# Code here
comparison = np.array_equal(max_result, sliced_result)
print(f"COMPARISON = {comparison}")

TEST ARRAY = [[-0.46118944 -0.0974952  -0.20484229  0.04619452]
 [ 1.41841791 -0.00991111  1.1387788  -0.81681026]
 [ 0.24389844  0.84352192  1.40405811  0.4520734 ]
 [ 0.12206156 -0.34262404  0.99391765 -1.60244757]
 [ 1.12392543  0.41030613 -0.53722452  0.03229528]
 [-0.34989667  0.71330061  0.08127985 -1.3897264 ]
 [-0.09041763 -0.53086141  0.0466377   1.36527838]
 [ 0.42376563 -2.05008235  0.08669888  2.3850152 ]
 [-1.78423076  0.32264852 -1.05067373  0.6490321 ]
 [ 1.72241894 -0.31418713  0.22985337  1.81708421]
 [-1.24373372 -0.0112101  -0.70031067  0.50849047]
 [ 0.8323522   0.8270553   1.44008373  0.3430716 ]]
RESULT [[-0.25092173 -0.18261117 -0.45959528]
 [ 0.83205024  0.53504167  1.43166912]
 [ 1.49685691  1.36341458  1.03226284]
 [ 0.26686845 -0.16460704  0.15051035]
 [ 0.07429546 -0.20555763  0.77262872]
 [ 0.29412694 -0.65251177 -0.28756689]
 [-0.1651072   0.70180016  0.03503517]
 [-0.8958975   1.18036021  0.24084651]
 [-0.652656   -0.56998049 -1.63243457]
 [ 0.39035343  1

## Lets start with the Feed forward pass

In [ ]:
# Implement the forward pass of the following neural network structure
# The arrows show only in the forward direction (we discuss backprogation later)
# More instructions below the image

from IPython.display import Image
Image(filename='feed_forward.png')

In [5]:
# All the following initializations are to be created with a random normal distribution

# Initialize the layers and name them w_0, w_1 and w_2
# w_0 is connected to the input (left side), w_1 is the middle part of the network and w_2 is connected to the output (right side)
# The layers are no vectors! The layers represent an input dimension and output dimension and are therefore matrices!

# Code here
w_0 = np.array(np.random.randn(2,3))
w_1 = np.array(np.random.randn(3,3))
w_2 = np.array(np.random.randn(3,2))


# Use the vector _input as the network's input
_input = np.random.randn(2)


In [6]:
# Perform the matrix multiplications to get the output (print the output)

# Code here
output_layer_0 = w_0.T.dot(_input)
output_layer_1 = w_1.T.dot(output_layer_0)
final_output = w_2.T.dot(output_layer_1)

print(final_output)

[3.89764492 9.32266905]


In [7]:
# Set all weight except one path to zero and compare the result of the output to your own (path) calculations.
# A path is defined here as one input to output connection by passing only one node per layer.
# Is the result correct?

# Code here
w_0_zeroed = np.zeros_like(w_0)
w_1_zeroed = np.zeros_like(w_1)
w_2_zeroed = np.zeros_like(w_2)


w_0_zeroed[0, 2] = w_0[0, 2]
w_1_zeroed[2, 2] = w_1[2, 2]
w_2_zeroed[2, 1] = w_2[2, 1]


output_layer_0_zeroed = w_0_zeroed.T.dot(_input)
output_layer_1_zeroed = w_1_zeroed.T.dot(output_layer_0_zeroed)
final_output_zeroed = w_2_zeroed.T.dot(output_layer_1_zeroed)

print(final_output_zeroed)

[ 0.         -0.12286137]
